name: ati
description: ATI Buscador y Comparador.
publish_to: 'none'
version: 0.7.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^10.0.0
  googleapis_auth: ^1.3.1
  pdf: ^3.9.0
  responsive_grid: ^2.1.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.18
  swipeable_page_route: ^0.3.0
  url_launcher: ^6.1.10
  google_sign_in: ^6.0.1
  auth_buttons: ^3.0.0
  delayed_display: ^2.0.0
  fade_out_particle: ^1.2.1
  firebase_auth: ^4.2.9
  firebase_auth_web: ^5.2.8
  firebase_core: ^2.7.0
  data_table_2: ^2.3.12
  dropdown_button2: ^2.0.0
  printing: ^5.10.1
  xml2json: ^5.3.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_speed_dial: ^6.2.0
  file_picker: ^5.2.7
  flutter_gradient_colors: ^2.1.1
  responsive_grid_list: ^1.3.1
  dio: ^5.2.0+1
  flutter_tableview: ^1.0.1
  mysql1: ^0.20.0
  flutter_form_builder: ^7.7.0
  flutter_datetime_picker: ^1.5.1
  flutter_rounded_date_picker: ^3.0.4
  table_calendar: ^3.0.8
  sqflite_common_ffi: ^2.2.5
  sqflite_common_ffi_web: ^0.3.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
